import './login';
import './modules';
import './modal/time';
import './modal/velocity';
import './modal/sleep-mode';
import './modal/speech';
import './modal/security';
import './modal/recommendation';
import './modal/additional-modal';